# Generated by Django 2.0 on 2019-07-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Float_Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Int_Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=140)),
                ('type', models.IntegerField(choices=[(1, 'FLOAT'), (2, 'INT')])),
                ('raw_value', models.CharField(max_length=32)),
                ('float_eng_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Float_Sensor')),
                ('int_eng_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Int_Sensor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
