# Generated by Django 2.0 on 2019-07-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=140)),
                ('raw_value', models.CharField(max_length=32)),
                ('eng_value', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='float_eng_value',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='int_eng_value',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Float_Sensor',
        ),
        migrations.DeleteModel(
            name='Int_Sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
