# Generated by Django 2.0 on 2019-07-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='owner',
        ),
    ]
