# Generated by Django 2.0 on 2019-07-13 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0002_auto_20190707_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='f_data',
            new_name='Fdata',
        ),
    ]
