# Generated by Django 2.0 on 2019-07-22 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_sensor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
