# Generated by Django 2.0 on 2019-07-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190713_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdata',
            old_name='eng_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='fdata',
            name='raw_value',
        ),
    ]
