# Generated by Django 2.0 on 2019-07-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_fdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fdata', to='Main.Sensor'),
        ),
    ]
