# Generated by Django 2.0 on 2019-07-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190723_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdata',
            name='timestamp',
        ),
    ]
